#index:
#    path: /
#    controller: App\Controller\DefaultController::index
    
index:
    path: /
    methods: GET
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\PostesController::liste
app_login:
    path: /login
    methods: POST|GETR
    controller: App\Controller\SecurityController::login

attributiondelete:
    path: /api/attributions/delete
    methods: POST
    controller: App\Controller\AttributionsController::delete

addattribution:
    path: /api/attributions/add
    methods: POST
    controller: App\Controller\AttributionsController::add

allposte:
    path: /api/postes
    methods: GET
    controller: App\Controller\AttributionsController::getPostes

addPoste:
    path: /api/postes/add
    methods: POST
    controller: App\Controller\PostesController::add
getClient:
    path : /api/clients
    methods: GET
    controller: App\Controller\ClientsController::index
addClient:
    path : /api/clients/add
    methods: POST
    controller: App\Controller\ClientsController::add

app_logout:
    path: /logout
    methods: get
    controller: App\Controller\SecurityController::logout
